version: '3'

services:

    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www/rd
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8005:80"
        depends_on:
            - app
        container_name: rd_nginx
        networks:
            - rd_net

    app:
        build:
            context: ./
            dockerfile: _docker/app/Dockerfile_local
        volumes:
            - ./:/var/www/rd
            - ./_docker/app/zzz-xdebug.ini:/usr/local/etc/php/conf.d/zzz-xdebug.ini
        container_name: rd_app
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            PHP_IDE_CONFIG: "serverName=rd"
        networks:
            - rd_net

networks:
    rd_net:
        driver: bridge
